[env]
TERM = "xterm-256color"

[terminal]
shell = "tmux"

[font]
normal = { family = "JetBrains Mono", style = "Regular" }

[keyboard]
bindings = [
  { mods = "Control | Super", key = "k", action = "IncreaseFontSize" },
  { mods = "Control | Super", key = "j", action = "DecreaseFontSize" },

  # unmap
  { mode = "Vi", key = "i", action = "ReceiveChar" },
  { mode = "Vi", key = "w", action = "ReceiveChar" },
  { mods = "Control", key = "+", action = "ReceiveChar" },
  { mods = "Control", key = "=", action = "ReceiveChar" },
  { mods = "Control", key = "-", action = "ReceiveChar" },
]

[colors.primary]
foreground = "#d8d8d8"
background = "#11111b"

[colors.normal]
black = "#171421"
red = "#df4444"
green = "#84d800"
yellow = "#de941a"
blue = "#4089e1"
magenta = "#c061cb"
cyan = "#2aa1b3"
white = "#d0cfcc"

[colors.bright]
black = "#5e5c64"
red = "#e05555"
green = "#87ff00"
yellow = "#e9aa43"
blue = "#89b4fa"
magenta = "#d053b6"
cyan = "#33c6de"
white = "#ffffff"

[colors.dim]
black = "#0f0f0f"
red = "#712b2b"
green = "#5f6f3a"
yellow = "#a17e4d"
blue = "#456877"
magenta = "#704d68"
cyan = "#4d7770"
white = "#8e8e8e"
