require 'plugin/autoclose-nvim'
require 'plugin/catppucin'
require 'plugin/lualine'
require 'plugin/dashboard'
require 'plugin/formatter'
require 'plugin/neo-tree'
require 'plugin/bufferline' -- to get neo-tree's hl group, bufferline must be import after it.
require 'plugin/nvim-ufo'
require 'plugin/colorizer'
require 'plugin/nvim-notify' -- noice:dep
require 'plugin/noice'
require 'plugin/indent-blankline-nvim'
require 'plugin/rainbow-delimiters'
require 'plugin/todo-comments'
require 'plugin/gitsigns-nvim'

require 'plugin/nvim-bufdel'
require 'plugin/nvim-cmp'
require 'plugin/treesitter'
require 'plugin/lsp-config'
require 'plugin/lightspeed-nvim'
