local window = {
  ['P']             = '',
  ['l']             = '',
  ['S']             = '',
  ['s']             = '',
  ['t']             = '',
  ['w']             = '',
  ['C']             = '',
  ['z']             = '',
  ['a']             = '',
  ['A']             = '',
  ['d']             = '',
  ['r']             = '',
  ['y']             = '',
  ['x']             = '',
  ['c']             = '',
  ['m']             = '',
  ['q']             = '',
  ['R']             = '',
  ['?']             = '',
  ['<']             = '',
  ['>']             = '',

  ['i']             = 'show_file_details',
  ['p']             = { 'toggle_preview', config = { use_float = false, use_image_nvim = false } },
  ['<Cr>']          = 'open',
  ['<M-j>']         = 'open',
  ['<M-k>']         = 'close_node',
  ['<C-;>']         = 'next_source',
  ['<Esc>']         = 'cancel',
  ['<Tab>']         = 'refresh',
  ['<Space>']       = { 'toggle_node', nowait = false },
  ['<2-LeftMouse>'] = 'open',
}

local filesystem = {
  ['.']     = '',
  ['f']     = '',
  ['H']     = '',
  ['D']     = '',
  ['#']     = '',
  ['[g']    = '',
  [']g']    = '',
  ['o']     = '',
  ['oc']    = '',
  ['od']    = '',
  ['og']    = '',
  ['om']    = '',
  ['on']    = '',
  ['os']    = '',
  ['ot']    = '',
  ['<Bs>']  = '',
  ['<C-x>'] = '',

  ['a']     = { 'add', config = { show_path = 'none' } },
  ['d']     = 'delete',
  ['r']     = 'rename',
  ['/']     = 'fuzzy_finder',
  ['c']     = 'copy',
  ['1']     = 'navigate_up',
  ['2']     = 'set_root',
  ['e']     = 'close_window',
}

local buffers = {
  ['.']    = '',
  ['o']    = '',
  ['oc']   = '',
  ['od']   = '',
  ['om']   = '',
  ['on']   = '',
  ['os']   = '',
  ['ot']   = '',
  ['bd']   = '',
  ['<Bs>'] = '',

  ['q']    = 'buffer_delete',
  ['/']    = 'fuzzy_finder',
}

local git_status = {
  ['o']  = '',
  ['A']  = '',
  ['gu'] = '',
  ['ga'] = '',
  ['gr'] = '',
  ['gc'] = '',
  ['gp'] = '',
  ['gg'] = '',
  ['oc'] = '',
  ['od'] = '',
  ['om'] = '',
  ['on'] = '',
  ['os'] = '',
  ['ot'] = '',
}

return {
  window = window,
  filesystem = filesystem,
  buffers = buffers,
  git_status = git_status,
}
